# server配置
server:
  port: 8080
  servlet:
    context-path: /

# 连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql:///blog
      username: root
      password: '2001214' #连不上用单引号包住
      driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis-plus的配置
mybatis-plus:
  type-aliases-package: com.example.springbootblogdemo.pojo #类别名配置
  global-config:
    db-config:
      logic-delete-field: isDeleted  #全局逻辑删除
      id-type: auto #主键策略自增长
      #table-prefix: news_ # 设置表的前缀
      # auto-mapping-behavior: full  自动映射 方便多表省略非主键字组的书写
      #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #在控制台输出sql语句的日志
      map-underscore-to-camel-case: true #驼峰式 mybatisplus已经为我们默认为true了
      #mapper-locations: classpath:/mapper/*.xml  #mapperxml位置 mybatis-plus现在不用了,默认mapper.xml文件 指定位置就是mapper文件夹
      #mapperxml文件的位置   settings的配置  别名的配置...

